name: Run scan

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: akto-api-security/run-scan@v1.0.5
        with:
          AKTO_DASHBOARD_URL: https://flash.staging.akto.io
          AKTO_API_KEY: ${{secrets.AKTO_API_KEY}}
          AKTO_TEST_ID: 65590b1ce9fca33d79d45440
          START_TIME_DELAY: 2
          OVERRIDEN_TEST_APP_URL: https://ironman.demo.akto.io:443
